apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-simulator
  labels:
    app: app-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-simulator
  template:
    metadata:
      labels:
        app: app-simulator
    spec:
      imagePullSecrets:
        - name: my-dockerhub-secret
      containers:
        - name: app-simulator
          image: togrulmirzoev/app-simulator-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres-service:5432/postgres"

---
apiVersion: v1
kind: Service
metadata:
  name: app-simulator-service
spec:
  type: NodePort
  selector:
    app: app-simulator
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "postgres"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-storage
      volumes:
        - name: postgres-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
